[run]
init_cmds = [["go", "install"]]
watch_all = true
watch_dirs = [
	"$WORKDIR/cmd",
	"$WORKDIR/modules",
]
watch_exts = [".go"]
build_delay = 1500
cmds = [
	["go", "install"]
]

[sync]
listen_addr = "0.0.0.0:5050"
remote_addr = "192.168.1.11:5050"